spring.application.name=preguntas
server.port=8081

spring.datasource.url=jdbc:postgresql://ep-long-rain-aibyq679.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_yCSXg6mxi9zo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.cloud.config.enabled=false

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
