spring.application.name=preguntas

server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d98ja5jtqb8s73fo40b0-a:5432/postgres_proyect_vision
spring.datasource.username=postgres_proyect_vision_user
spring.datasource.password=7bzUaZXhOY5vO5mzWXvK5Xs2uQpjSpIT
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cloud.config.enabled=false

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB